Repository UBC-MDS/simpler_eda, pull requests merged in 2021-03, with the labels that each got.

#25 Add categorical function
  simpler_eda/categorical_eda.py
  tests/test_categorical_eda.py
Labels: development

#26 Numerical function code and tests
  simpler_eda/numerical_eda.py
  tests/test_numerical_eda.py
Labels: development

#24 first draft of unit test and function code
  poetry.lock
  pyproject.toml
  simpler_eda/corr_map.py
  tests/test_corr_map.py
Labels: development

#33 updated according to milestone
  .github/workflows/build.yml
Labels: development

#36 Git action
  tests/test_corr_map.py
  tests/test_simpler_eda.py
Labels: bug

#40 update deploy for git action
  .github/workflows/deploy.yml
Labels: enhancement

#44 fix: added badge for release
  README.md
Labels: development
