Repository UBC-MDS/simpler_eda, pull requests merged in 2021-02, with the labels that each got.

#11 updated contact email, and contributor section in README
  CONDUCT.rst
  CONTRIBUTING.rst
  README.md
Labels: task

#12 Proposal writeup and Function for numerical plots
  README.md
  simpler_eda/numerical_eda.py
Labels: development

#13 corr_map function docstring v0.1
  simpler_eda/corr_map.py
Labels: development

#16 Changes to the format of the documentation
  simpler_eda/numerical_eda.py
Labels: documentation
